# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: ict.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.ict.com
    Template:
      Count: 1 # peer의 갯수
    Users:
      Count: 1 # 기등록된 application 사용자 인증서 갯수
  - Name: Org2
    Domain: org2.ict.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.ict.com
    Template:
      Count: 1
    Users:
      Count: 1

